service:
  name: "user-service"
  ip: "127.0.0.1"
  port: 8085
  weight: 10
  enable: true
  healthy: true
  ephemeral: true
  group_name: "DEFAULT_GROUP"
  metadata:
    language: "go"
    go_version: "1.23"
    app: "user"
    team: "personal"

config:
  data_id: "user2-config.yaml"
  group: "DEFAULT_GROUP"
  content: |
    service:
      name: user-service
      version: "1.0.0"
    database:
      host: "localhost"
      port: 3306